# Generated by Django 5.0.4 on 2024-04-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_index_councellor_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_councellor',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
