# Generated by Django 5.0.4 on 2024-04-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_index_councellor_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index_councellor',
            new_name='Admissioncouncellor',
        ),
    ]
