from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('about_overview/', views.about_overview),
    path('vision_mission/', views.vision_mission),
    path('leadershipteam/', views.leadershipteam),
    path('ranking_recognition/', views.ranking_recognition),
    path('collaborations/', views.collaborations),
    path('blogs/', views.blogs),
    path('Social_responsibilities/', views.Social_responsibilities),
    path('admissions_overview/', views.admissions_overview),
    path('ug_programs/', views.ug_programs),
    path('pg_programs/', views.pg_programs),
    path('diploma_programs/', views.diploma_programs),
    path('other_short_programs/', views.other_short_programs),
    path('scholorship/', views.scholorship),
    path('career_guidance/', views.career_guidance),
    path('campuses/', views.campuses),
    path('learning_methodology/', views.learning_methodology),
    path('library_recourse_center/', views.library_recourse_center),
    path('allied_departments/', views.allied_departments),
    path('sports_recreation/', views.sports_recreation),
    path('hostal_facilities/', views.hostal_facilities),
    path('industry_visits/', views.industry_visits),
    path('placements_overview/', views.placements_overview),
    path('placement_training/', views.placement_training),
    path('job_fairs_events/', views.job_fairs_events),
    path('current_offers/', views.current_offers),
    path('internship_opportunities/', views.internship_opportunities),
    path('part_time_opportunities/', views.part_time_opportunities),
    path('scholorship/', views.scholorship),
    path('contact_us/', views.contact_us),
    path('parscore/', views.parscore),  
]
